name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - arch: x64
            os: windows-latest
          - arch: arm64
            os: windows-11-arm
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install WiX Toolset
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip" -OutFile "wix314-binaries.zip"
          Expand-Archive -Path "wix314-binaries.zip" -DestinationPath "C:\wix"
          echo "C:\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Windows ${{ matrix.arch }}
        run: npm run make
        env:
          npm_config_target_arch: ${{ matrix.arch }}

      - name: Upload Windows ${{ matrix.arch }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apksignergui_${{ github.ref_name || inputs.version || 'dev' }}_${{ matrix.arch == 'x64' && 'amd64' || matrix.arch }}_windows
          path: out/make/**/*

  build-macos:
    strategy:
      matrix:
        include:
          - arch: x64
            os: macos-13
          - arch: arm64
            os: macos-latest
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build macOS ${{ matrix.arch }}
        run: npm run make
        env:
          npm_config_target_arch: ${{ matrix.arch }}

      - name: Upload macOS ${{ matrix.arch }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apksignergui_${{ github.ref_name || inputs.version || 'dev' }}_${{ matrix.arch == 'x64' && 'amd64' || matrix.arch }}_macos
          path: out/make/**/*

  build-linux:
    strategy:
      matrix:
        include:
          - arch: x64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Linux ${{ matrix.arch }}
        run: npm run make
        env:
          npm_config_target_arch: ${{ matrix.arch }}

      - name: Upload Linux ${{ matrix.arch }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apksignergui_${{ github.ref_name || inputs.version || 'dev' }}_${{ matrix.arch == 'x64' && 'amd64' || matrix.arch }}_linux
          path: out/make/**/*