name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install WiX Toolset (Windows only)
        if: matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm'
        run: |
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip" -OutFile "wix314-binaries.zip"
          Expand-Archive -Path "wix314-binaries.zip" -DestinationPath "C:\wix"
          echo "C:\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Test package build
        run: npm run package

      - name: Test make build (sample)
        run: npm run make
        continue-on-error: true