name: Build for AppTest

on:
  push:
    branches: [develop]

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get version from package.json
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

  build:
    needs: get-version
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            platform: win32
            arch: x64
            name: Windows x64
            platform_name: windows
          - os: windows-11-arm
            platform: win32
            arch: arm64
            name: Windows ARM64
            platform_name: windows

          # macOS builds
          - os: macos-13
            platform: darwin
            arch: x64
            name: macOS Intel
            platform_name: macos
          - os: macos-latest
            platform: darwin
            arch: arm64
            name: macOS Apple Silicon
            platform_name: macos

          # Linux builds
          - os: ubuntu-latest
            platform: linux
            arch: x64
            name: Linux x64
            platform_name: linux
          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64
            name: Linux ARM64
            platform_name: linux

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install WiX Toolset (Windows only)
        if: matrix.platform == 'win32'
        run: |
          # Download and install WiX Toolset v3
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip" -OutFile "wix314-binaries.zip"
          Expand-Archive -Path "wix314-binaries.zip" -DestinationPath "C:\wix"
          echo "C:\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build application
        run: npm run make
        env:
          ELECTRON_BUILDER_ARCH: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apksignergui_${{ needs.get-version.outputs.version }}_${{ matrix.arch == 'x64' && 'amd64' || matrix.arch }}_${{ matrix.platform }}
          path: |
            ./out/*
          retention-days: 30
